"$schema" = 'https://starship.rs/config-schema.json'
palette = 'catppuccin'

format = """
[╭─](bold lavender)[](lavender)\
$os\
[](bold fg:lavender)[](bold bg:lavender fg:transparent)\
$username\
[](bold fg:lavender)[](bold bg:lavender fg:transparent)\
$directory\
[](bold fg:lavender)\
$git_branch $git_status\
$fill\
$line_break[╰─](bold lavender)$character"""

[os]
disabled = false
style = "bg:lavender fg:crust"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:lavender fg:crust"
style_root = "bg:lavender fg:crust"
format = '[ $user ]($style)'

[directory]
style = "fg:crust bg:lavender"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = " "
style = "fg:green"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:green"
format = '[$all_status$ahead_behind]($style)'

[line_break]
disabled = false

[fill]
symbol = ' '

[character]
disabled = false
success_symbol = '[»](bold fg:lavender)'
error_symbol = '[»](bold fg:red)'
vimcmd_symbol = '[](bold fg:lavender)'

[palettes.catppuccin]
theme = '#A7B48F'
crust = '#11111b'
text = '#cdd6f4'
red =   '#f38ba8'
blue = '#89b4fa'
teal = '#94e2d5'
sky = '#89dceb'
pink = '#f5c2e7'
green = '#a6e3a1'
yellow = '#f9e2af'
maroon = '#eba0ac'
lavender = '#b4befe'
rosewater = '#f5e0dc'
peach = '#fab387'
mauve = '#cba6f7'
flamingo = '#f2cdcd'
sapphire = '#74c7ec'
transparent = '#1F1F2F'
