[bar.default]
capsule = true
end = [ "tray", "notifications", "volume", "bluetooth", "network", "mirror", "battery" ]
font_family = "Inter"
margin_edge = 5
margin_ends = 240
margin_opposite_edge = 1
reserve_space = false
smart_auto_hide = true
start = [ "workspaces", "Wayvibes-Toggle", "cpu", "ram", "bar", "privacy" ]

    [bar.default.actions]
    middle = "none"

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "dark_mode"

[[control_center.shortcuts]]
type = "8bury/lid-guard:lid-guard-toggle"

[[control_center.shortcuts]]
type = "noctalia/screen_recorder:toggle"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001", "desktop-widget-0000000000000002", "desktop-widget-0000000000000007" ]

    [desktop_widgets.grid]
    cell_size = 8
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 280.0
    box_width = 280.0
    cx = 268.0
    cy = 256.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        bloom_intensity = 0.70000000000000007
        inner_diameter = 0.70000000000000007
        secondary_color = "primary"
        visualization_mode = "rings"

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 280.0
    box_width = 280.0
    cx = 1604.0
    cy = 716.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = false
        bloom_intensity = 0.60000000000000009
        secondary_color = "primary"
        visualization_mode = "rings"

    [desktop_widgets.widget.desktop-widget-0000000000000007]
    box_height = 32.0
    box_width = 224.0
    cx = 992.0
    cy = 308.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000007.settings]
        background = true
        bands = 32
        centered = false
        mirrored = true
        show_when_idle = true

[location]
address = "Sargodha, Pakistan"

[lockscreen]
fingerprint = false

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 103.0
    box_width = 400.0
    cx = 768.0
    cy = 752.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.90000000000000002
        background_radius = 12.0
        center_password_text = true
        input_opacity = 1.0
        input_radius = 6.0
        layout = "compact"
        show_caps_lock = false
        show_keyboard_layout = false
        show_login_button = false
        show_media = false
        show_session_buttons = true
        show_weather = false

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 103.0
    box_width = 400.0
    cx = 944.0
    cy = 889.0
    enabled = false
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_weather = true

[nightlight]
force = true

[osd.kinds]
bluetooth = false
caffeine = false
dnd = false
lock_keys = false
power_profile = false
wifi = false

[plugin_settings."noctalia/screen_recorder"]
copy_to_clipboard = true
resolution = "1920x1080"

[plugin_settings."oldirtty/color_picker"]
hyprpicker-cursor = true
hyprpicker-lowercase = true

[plugins]
enabled = [
    "oldirtty/color_picker",
    "noctalia/screen_recorder",
    "noctalia/notes",
    "8bury/lid-guard",
    "elijaharch/wl-screen-mirror"
]

[shell]
app_icon_color = "on_surface"
app_icon_colorize = true
clipboard_enabled = false
corner_radius_scale = 1.2000000178813934
font_family = "Inter"
lang = "en"
polkit_agent = true
screen_time_enabled = true

    [shell.animation]
    speed = 2.0000000298023224

    [shell.launcher]
    compact = true

    [shell.panel]
    control_center_placement = "floating"
    control_center_position = "center"
    session_placement = "floating"
    session_position = "center"
    wallpaper_placement = "floating"
    wallpaper_position = "center"

    [shell.screenshot]
    directory = "/home/waleed/Pictures/Screenshots"

[system.monitor]
ram_pct_activity_threshold = 80

[theme]
builtin = "Ayu"
community_palette = "Catppuccin Lavender"
custom_palette = "catppuccin-custom"
mode = "dark"
source = "community"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "kcolorscheme", "niri", "qt" ]
    community_ids = [ "obsidian", "bat", "discord", "lazygit", "obs", "yazi" ]

[wallpaper]
directory = "/home/waleed/Pictures/Wallpapers"
transition = [ "disc" ]
transition_on_startup = true

    [wallpaper.default]
    path = "/home/waleed/Pictures/Wallpapers/catppuccin-mocha/31.jpg"

    [wallpaper.last]
    path = "/home/waleed/Pictures/Wallpapers/catppuccin-mocha/31.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/waleed/Pictures/Wallpapers/catppuccin-mocha/31.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/waleed/Pictures/Wallpapers/catppuccin-mocha/31.jpg"

    [[wallpaper.favorite]]
    community_palette = "Catppuccin Lavender"
    palette_source = "community"
    path = "/home/waleed/Pictures/Wallpapers/catppuccin-mocha/31.jpg"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    community_palette = "Catppuccin Lavender"
    palette_source = "community"
    path = "/home/waleed/Pictures/Wallpapers/catppuccin-mocha/29.png"
    theme_mode = "dark"

[widget.Wayvibes-Toggle]
glyph = "keyboard"
type = "custom_button"

    [widget.Wayvibes-Toggle.actions]
    left = "exec ~/scripts/toggle-wayvibes.sh"

[widget.active_window]
display = "text_only"
enabled = false
max_length = 200
min_length = 10

[widget.bar]
show_idle_on_horizontal = false
type = "noctalia/timer:bar"

[widget.clock]
anchor = true
format = "{:%I:%M %p - %a %b %-d}"

[widget.control-center]
glyph = "linux-archlinux"

[widget.lock_keys]
hide_when_off = true

[widget.mirror]
color = "on_surface"
icon_color = "on_surface"
type = "elijaharch/wl-screen-mirror:mirror"

[widget.network]
show_label = false

[widget.privacy]
active_color = "on_surface"
hide_inactive = true
icon_spacing = 8

[widget.tray]
hidden = [ "nm-applet", "wayscriber", "motrix-next", "motrix", "vocalinux", "vocalinux-gui" ]
pinned = [ "kdeconnect" ]

[widget.volume]
mute_color = "on_surface"
show_label = false

[widget.workspaces]
display = "none"
empty_color = "on_secondary"
hide_when_empty = true
occupied_color = "outline"
